### ISSUE TITLE
Question about 'data_len'

### ISSUE THREAD

**Issue by wengzp1** [RuihanGao/visual-tactile-synthesis#2]
Hi. May I ask if changing the value of 'data_len' to 100 will have any impact on the final rendering result?For example, does it have an impact on the ‘I_LPIPS’ indicator？

**Comment by RuihanGao** [comment]
During training, `data_len` controls how much augmentation we perform for single-image translation and metrics like `I_LPIPS` is computed by taking mean, so the values may fluctuate across different iterations. We set `data_len` to a large number to allow more variation during training and thus better generalizability. 
During inference, we only have one test sketch, so we set `data_len=1` and the metrics should be consistent.

**Comment by wengzp1** [comment]
> 在训练期间，`data_len`控制我们对单图像翻译执行多少增强，并且`I_LPIPS`通过取均值计算类似的指标，因此值可能会在不同的迭代中波动。我们设置`data_len`了一个很大的数字，以允许在训练过程中有更多的变化，从而提高泛化能力。 在推理过程中，我们只有一个测试草图，所以我们设置`data_len=1`和指标应该是一致的。

Thank you for your reply.I also want to know whether the quantitative results in the paper such as "Visual LPIPS" are obtained from the average of 20 data objects?

**Comment by RuihanGao** [comment]
Yes, they are

**Comment by wengzp1** [comment]
> Yes, they are

OK,thank you
